---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
  - name: centos-7.0
  - name: fedora-20
  - name: debian-7.8
  - name: debian-8.1
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:

  - name: default
    run_list:
      - recipe[rngd-tools::default]
