---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.6
  - name: centos-7.0
  - name: fedora-20
  - name: debian-7.8
  - name: debian-8.1
    driver:
      box: opscode-debian-8.1
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-8.1_chef-provisionerless.box
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:

  - name: default
    run_list:
      - recipe[rngd-tools::default]
